SafeShop.Application/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SafeShop.Application.Requests;
using SafeShop.Application.ViewModels;
using System.Net.Http.Headers;

namespace SafeShop.Application.Controllers
{
    public class CartController : Controller
    {
        private readonly IHttpClientFactory factory;

        public CartController(IHttpClientFactory factory)
        {
            this.factory = factory;
        }

        public async Task<IActionResult> Index()
        {
            var httpClient = factory.CreateClient("SafeShopClient");
            SetBearerToken(httpClient);
            CartViewModel cart = new CartViewModel() { Products = Enumerable.Empty<CartProductViewModel>() };
            string cartId = GetCartId();
            if (cartId != string.Empty)
            {
                var response = await httpClient.GetAsync($"cart/{cartId}");
                response.EnsureSuccessStatusCode();
                var content = await response.Content.ReadAsStringAsync();
                cart = JsonConvert.DeserializeObject<CartViewModel>(content);
            }
            return View(cart);
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            var httpClient = factory.CreateClient("SafeShopClient");
            SetBearerToken(httpClient);
            var response = await httpClient.DeleteAsync($"cartproducts/{id}");
            response.EnsureSuccessStatusCode();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditQuantity(string quantity, Guid productId)
        {
            var httpClient = factory.CreateClient("SafeShopClient");
            SetBearerToken(httpClient);
            ChangeProductQuantityRequest request = new ChangeProductQuantityRequest() { Quantity = int.Parse(quantity) };
            string jsonBody = JsonConvert.SerializeObject(request);
            StringContent body = new StringContent(jsonBody, encoding: System.Text.Encoding.UTF8, "application/json");
            var response = await httpClient.PutAsync($"cartproducts/{productId}", body);
            response.EnsureSuccessStatusCode();
            return RedirectToAction("Index");
        }

        public IActionResult Order()
        {
            return RedirectToAction("Index", "Order");
        }

        private string GetCartId()
        {
            if(Request.Cookies.ContainsKey("SID"))
            {
                return Request.Cookies["SID"];
            } else
            {
                return string.Empty;
            }
        }

        private void SetBearerToken(HttpClient httpClient)
        {
            if(Request.Cookies.ContainsKey("AccessID"))
            {
                string accessToken = Request.Cookies["AccessID"].ToString();
                httpClient.DefaultRequestHeaders.Authorization = 
                    new AuthenticationHeaderValue($"Bearer", $"{accessToken}");

            }
        }
    }
}

SafeShop.Application/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SafeShop.Application.ViewModels;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace SafeShop.Application.Controllers
{
    public class LoginController : Controller
    {
        private readonly IHttpClientFactory factory;

        public LoginController(IHttpClientFactory factory)
        {
            this.factory = factory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginFormViewModel loginForm)
        {
            var client = factory.CreateClient("SafeShopClient");
            string jsonBody = JsonConvert.SerializeObject(loginForm);
            StringContent body = new StringContent(jsonBody, encoding: System.Text.Encoding.UTF8, "application/json");
            var response = await client.PostAsync("auth/login", body);
            if(!response.IsSuccessStatusCode)
            {
                TempData["ErrorMessage"] = "Nieprawidłowe dane logowania. Sprawdź, czy nie masz wciśniętego klawisza Caps-Lock.";
                return View();
            }
            string token = await response.Content.ReadAsStringAsync();
            TokenToCookie(token);
            await SetClaims(token);
            return Redirect("/");
        }

        public IActionResult Logout()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return Redirect("/");
        }

        private void TokenToCookie(string token)
        {     
            CookieOptions options = new CookieOptions();
            options.HttpOnly = true;
            options.Secure = true;
            options.SameSite = SameSiteMode.Strict;
            options.Expires = DateTimeOffset.UtcNow.AddHours(1);
            Response.Cookies.Append("AccessID", token, options);
        }

        private async Task SetClaims(string token)
        {
            var handler = new JwtSecurityTokenHandler();
            var jsonToken = handler.ReadToken(token);
            var tokenS = jsonToken as JwtSecurityToken;
            var claims = new List<Claim>();
            claims.Add(tokenS.Claims.First(claim => claim.Type == ClaimTypes.Email));
            claims.Add(tokenS.Claims.First(claim => claim.Type == ClaimTypes.Surname));
            claims.Add(tokenS.Claims.First(claim => claim.Type == ClaimTypes.Role));
            claims.Add(tokenS.Claims.First(claim => claim.Type == "ID"));
            var userIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
            await HttpContext.SignInAsync(principal);
        }
    }
}

SafeShop.Application/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SafeShop.Application.Requests.Auth;
using SafeShop.Application.ViewModels;

namespace SafeShop.Application.Controllers
{
    public class RegisterController : Controller
    {
        private readonly IHttpClientFactory factory;

        public RegisterController(IHttpClientFactory factory)
        {
            this.factory = factory;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(RegisterFormViewModel registerForm)
        {
            if(!ModelState.IsValid)
            {
                return View(registerForm);
            }
            RegisterRequest request = new RegisterRequest(registerForm);
            var httpClient = factory.CreateClient("SafeShopClient");
            string jsonBody = JsonConvert.SerializeObject(request);
            StringContent body = new StringContent(jsonBody, encoding: System.Text.Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync($"auth/register", body);
            response.EnsureSuccessStatusCode();
            TempData["RegisterMessage"] = "Pomyślnie zarejestrowano konto. Możesz teraz się zalogować.";
            return RedirectToAction("Index", "Login");
        }
    }
}

SafeShop.Application/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SafeShop.Application.Requests;
using SafeShop.Application.Responses;
using SafeShop.Application.ViewModels;

namespace SafeShop.Application.Controllers
{
    public class ShopController : Controller
    {
        private readonly IHttpClientFactory factory;

        public ShopController(IHttpClientFactory factory)
        {
            this.factory = factory;
        }

        public async Task<IActionResult> Index(int pageNumber = 1)
        {
            var httpClient = factory.CreateClient("SafeShopClient");
            var response = await httpClient.GetAsync($"products?page={pageNumber}&size=15");
            response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            var products = JsonConvert.DeserializeObject<ProductListPageModel>(content);
            ViewData["PageNumber"] = pageNumber;
            return View(products);
        }

        public async Task<IActionResult> Details(Guid id)
        {
            string endpoint = $"products/{id}";
            if(Request.Cookies.ContainsKey("SID"))
            {
                endpoint += $"?cartId={Request.Cookies["SID"]}";
            }
            var httpClient = factory.CreateClient("SafeShopClient");
            var response = await httpClient.GetAsync(endpoint);
            response.EnsureSuccessStatusCode();
            var content = await response.Content.ReadAsStringAsync();
            var product = JsonConvert.DeserializeObject<ProductDetailsPageModel>(content);
            return View(product);
        }
        
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddToCart(int quantity, string productId)
        {
            AddProductToCartRequest request = new AddProductToCartRequest()
            {
                ProductID = Guid.Parse(productId),
                Quantity = quantity,
                UserID = GetIdFromClaim()
            };

            if (Request.Cookies.ContainsKey("SID"))
            {
                request.CartID = Guid.Parse(HttpContext.Request.Cookies["SID"].ToString());
            }
            var httpClient = factory.CreateClient("SafeShopClient");
            string jsonBody = JsonConvert.SerializeObject(request);
            StringContent body = new StringContent(jsonBody, encoding: System.Text.Encoding.UTF8, "application/json");
            var response = await httpClient.PostAsync($"cartproducts", body);
            response.EnsureSuccessStatusCode();
            if (!Request.Cookies.ContainsKey("SID"))
            {
                var content = await response.Content.ReadAsStringAsync();
                var resp = JsonConvert.DeserializeObject<AddProductToCartResponse>(content);
                CookieOptions options = new CookieOptions();
                options.HttpOnly = true;
                options.Secure = true;
                options.SameSite = SameSiteMode.Lax;
                options.Expires = DateTimeOffset.UtcNow.AddDays(7);
                Response.Cookies.Append("SID", resp.CartID.ToString(), options);
            }
            return RedirectToAction("Index");
        }

        private Guid GetIdFromClaim()
        {
            if(User.HasClaim(c => c.Type == "ID"))
            {
                return Guid.Parse(User.Claims.FirstOrDefault(c => c.Type == "ID").Value);
            }
            return Guid.Empty;
        }
    }
}

SafeShop.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SafeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SafeShop.Application.styles.css" asp-append-version="true" />
</head>
<body class="safeshop-menu">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SafeShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Shop" asp-action="Index">Sklep</a>
                        </li>
                        <li class="nav-item pl-3">
                            <a class="nav-link text-light" asp-area="" asp-controller="Cart" asp-action="Index">Koszyk</a>
                        </li>
                        @if (User.Identity.IsAuthenticated) {
                        <li class="nav-item pl-3">
                            <a class="nav-link text-light" asp-area="" asp-controller="OrderList" asp-action="Index">Lista zamówień</a>
                        </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Login" asp-action="Index">Logowanie</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Register" asp-action="Index">Rejestracja</a>
                            </li>
                        } 
                        else 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-controller="Login" asp-action="Logout">Wyloguj</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>